export default function Required() {
  const formCount = Number(sessionStorage.getItem("formCount"));
  const requiredFields = [
    "Business Name",
    "Business Registration Number",
    "Business Registration Date",
    "Business Telephone Number1",
    "Business Telephone Number2",
    "Nature of Business",
    "Business Sector",
    "Business Email Address",
    "Business Monthly Turnover",
    "Business Annual Turnover",
    "Business Employee Size",
    "Business Proposed Initial Deposit",
    "Business Office Address",
    "Business Mailing Email Address",
    "Business Bank1",
    "Business Bank2",
    "Business Bank3",
    "Business Account Name1",
    "Business Account Name2",
    "Business Account Name3",
    "Business Account Number1",
    "Business Account Number2",
    "Business Account Number3",
    "Priopertor-name",
    "priopertor-firm",
    "m-s-1",
    "m-s-2",
    "proprietor-signature-date",
    "proprietor-signature-day",
    "Proprietor Full Name",
    "priopertor-signature",
    "proprietor-address",
    "proprietor-witness-name",
    "priopertor-witness-signature",
    "proprietor-witness-occupation",
    "proprietor-witness-address",
    ...Array(formCount)
      .fill(null)
      .flatMap((_, index) => [
        `Next of Kin Gender${index + 1}`,
        `Identification${index + 1}`,
        `House${index + 1}`,
        `Gender${index + 1}`,
        `Marital-Status${index + 1}`,
        `Proprietor Surname${index + 1}`,
        `Proprietor Firstname${index + 1}`,
        `Proprietor Other Names${index + 1}`,
        `Proprietor Mother's Maiden Name${index + 1}`,
        `Proprietor DOB${index + 1}`,
        `Proprietor Title${index + 1}`,
        `Proprietor Place of Birth${index + 1}`,
        `Proprietor's Residence Permit Number${index + 1}`,
        `Proprietor's Permit Issue Date${index + 1}`,
        `Proprietor's Permit Expiry Date${index + 1}`,
        `Proprietor's TIN${index + 1}`,
        `Proprietor State of Origin${index + 1}`,
        `Proprietor LGA of Origin${index + 1}`,
        `Proprietor's Purpose of Account${index + 1}`,
        `Proprietor's Residential Address${index + 1}`,
        `Proprietor's Residence Street Name${index + 1}`,
        `Proprietor's Residence Landmark/Bus-Stop${index + 1}`,
        `Proprietor's Residence City/Town${index + 1}`,
        `Proprietor's Residence LGA${index + 1}`,
        `Proprietor's Residence State${index + 1}`,
        `First Proprietor's Phone Number${index + 1}`,
        `Second Proprietor's Phone Number${index + 1}`,
        `Proprietor's Email${index + 1}`,
        `Other means of Identification${index + 1}`,
        `Proprietor's ID Issue Date${index + 1}`,
        `Proprietor's ID Expiry Date${index + 1}`,
        `Proprietor's BVN${index + 1}`,
        `Next of Kin Surname${index + 1}`,
        `Next of Kin Gender${index + 1}`,
        `Next of Kin Firstname${index + 1}`,
        `Next of Kin Other Names${index + 1}`,
        `Next of Kin Title${index + 1}`,
        `Next of Kin DOB${index + 1}`,
        `Next of Kin Relationship${index + 1}`,
        `First Next of Kin Phone Number${index + 1}`,
        `Second Next of Kin of Phone Number${index + 1}`,
        `Next of Kin Email${index + 1}`,
        `Next of Kin Home Street Name${index + 1}`,
        `Next of Kin Home Adress${index + 1}`,
        `Next of Kin Home Landmark/Bus-Stop${index + 1}`,
        `Next of Kin Place of Work${index + 1}`,
        `Next of Kin Home City/Town${index + 1}`,
        `Next of Kin Home LGA${index + 1}`,
        `Next of Kin Home State${index + 1}`,
        `Affliated/Parent Company${index + 1}`,
        `Country of Affliated/Parent Company${index + 1}`,
        `Specimen Title${index + 1}`,
        `Specimen Name${index + 1}`,
        `Specimen Designation${index + 1}`,
        `Specimen BVN Number${index + 1}`,
        `Specimen-Signature${index + 1}`,
        `Specimen-Passport-Photograph${index + 1}`,
        `Specimen Signature Class${index + 1}`,
        `Specimen Account Name${index + 1}`,
        `Specimen Home Address${index + 1}`,
        `Specimen Phone Number${index + 1}`,
        `Specimen Account Number${index + 1}`,
      ]),
  ];
  return { requiredFields };
}
