export default function Required() {
  const requiredFields = [
    "business-name",
    "registration-number",
    "date-of-registration",
    "officetel1",
    "officetel2",
    "nature-of-business",
    "sector",
    "email",
    "monthly-business-turnover",
    "annually-business-turnover",
    "employee-count",
    "proposed-initial-deposit",
    "Priopertor-name",
    "priopertor-firm",
    "m-s-1",
    "m-s-2",
    "proprietor-signature-date",
    "proprietor-signature-day",
    "Proprietor Full Name",
    "priopertor-signature",
    "proprietor-address",
    "proprietor-witness-name",
    "priopertor-witness-signature",
    "proprietor-witness-occupation",
    "proprietor-witness-address",
    "proprietor-surname",
    "proprietor-firstname",
    "proprietor-othernames",
    "Proprietor Mother's Maiden Name",
    "proprietor-DOB",
    "proprietor-title",
    "proprietor-place-of-birth",
    "proprietor-residence-permit-number",
    "permit-issue-date",
    "permit-exp-date",
    "proprietor-TIN",
    "proprietor-purpose-of-account",
    "proprietor-residence-address",
    "Street Name",
    "Landmark/Bus-Stop",
    "City/Town",
    "Residence LGA",
    "Residence State",
    "Proprietor Phone Number (1)",
    "Proprietor Phone Number (2)",
    "Proprietor Email",
    "Other means of Identification",
    "ID-issue-date",
    "ID-exp-date",
    "Proprietor BVN",
    "Next of Kin Surname",
    "Next of Kin Firstname",
    "Next of Kin Other Names",
    "Next of Kin Title",
    "next-of-kin-DOB",
    "Next of Kin Relationship",
    "Next of Kin Phone Number (1)",
    "Next of Kin of Phone Number (2)",
    "Next of Kin Email",
    "Next of Kin Home Street Name",
    "Next of Kin Home Adress",
    "Next of Kin Home Landmark/Bus-Stop",
    "Next of Kin Place of Work",
    "Next of Kin Home City/Town",
    "Next of Kin Home LGA",
    "Next of Kin Home State",
    "Affliated/Parent Company",
    "Country of Affliated/Parent Company",
    "Signature of CSU Signature",
    "Account Officer Signature",
    "Collection Opening Form Request Date",
    "Collection Opening Form Completed Date",
    "Submission Opening Form Request Date",
    "Submission Opening Form Completed Date",
    "Identification Request Date",
    "Identification Completed Date",
    "International Passport Request Date",
    "International Passport Completed Date",
    "Driver's License Request Date",
    "Driver's License Completed Date",
    "Passport Photograph Request Date",
    "Passport Photograph Completed Date",
    "Verification of Signature Request Date",
    "Verification of Signature Completed Date",
    "Signature Card Request Date",
    "Signature Card Completed Date",
    "Mandate Request Date",
    "Mandate Completed Date",
    "Internal Reference Form Request Date",
    "Internal Reference Form Completed Date",
    "External Reference Form Request Date",
    "External Reference Form Completed Date",
    "Direct Reference Form Request Date",
    "Direct Reference Form Completed Date",
    "Application for Registration Request Date",
    "Application for Registration Completed Date",
    "Certificate of Registration Request Date",
    "Certificate of Registration Completed Date",
    "Search Report Request Date",
    "Search Report Completed Date",
    "Waived Document Request Date",
    "Waived Document Completed Date",
    "Deferred Document",
    "Deferral Period Request Date",
    "Deferral Period Completed Date",
    "Specimen Title1",
    "Specimen Name1",
    "Specimen Designation1",
    "Specimen BVN Number1",
    "Specimen-Signature1",
    "Specimen-Passport-Photograph1",
    "Specimen Signature Class1",
    "Specimen Account Name",
    "Specimen Home Address",
    "Specimen Phone Number",
    "accountnumber",
  ];
  return requiredFields;
}
